# Generated by Django 5.2.7 on 2025-11-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_id_alter_movie_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='background',
            field=models.ImageField(blank=True, null=True, upload_to='backgrounds'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_showcase',
            field=models.BooleanField(default=False),
        ),
    ]
